### ISSUE TITLE
view in different fonts

### ISSUE THREAD

**Issue by gaojunxin** [jazzband/prettytable#201] opened 2022-09-27 01:40 UTC
![image](https://user-images.githubusercontent.com/22878156/192411369-2f102231-9417-4f78-9d1d-a2304bd9280e.png)
在不同字体下，表格无法对齐。

**Comment by hugovk** [comment] 2022-09-27 04:34
This looks like a duplicate of https://github.com/jazzband/prettytable/issues/49, do any of the suggestions there help? Can you use another font?

**Comment by firai** [comment] 2023-07-11 06:28
Beyond the issue with Chinese characters possibly using a substitute font as in #49, this question seems to be asking for alignment with proportional fonts, which is essentially impossible for prettytable to achieve.

**Closed as not planned** 2023-07-11 07:53 UTC
