### ISSUE TITLE
Full-width characters cannot be wrapped correctly.

### ISSUE THREAD

**Issue by yeruizhi** [jazzband/prettytable#262] opened 2023-10-09 20:05 UTC
### Problem:
I want to put a long sentence in a cell, and it should be wrapped with given `max_table_width`.

It works well when all characters are half-width characters.  

```
┌──────────────────────────────────────────────────────────────────────────────────┐
│                                      暂放区                                      │
├──────────────────────────────────────────────────────────────────────────────────┤
│ Field 1                                                                          │
├──────────────────────────────────────────────────────────────────────────────────┤
│ abcd, abcd, abcd, abcd, abcd, abcd, abcd, abcd, abcd, abcd, abcd, abcd, abcd,    │
│ abcd, abcd, abcd, abcd, abcd, abcd                                               │
└──────────────────────────────────────────────────────────────────────────────────┘
```

But when some chinese characters (full-width characters) appeared in the row, the `max_table_width` cannot warp the line correctly. The sentence was wraped into several lines, but the line-width was not correct.

```
┌────────────────────────────────────────────────────────────────────────────────────┐
│                                       暂放区                                       │
├────────────────────────────────────────────────────────────────────────────────────┤
│ Field 1                                                                            │
├────────────────────────────────────────────────────────────────────────────────────┤
│ 数学-陈景润, 数学-陈景润, 数学-陈景润, 数学-陈景润, 语文-孔子, 语文-孔子, 英语-莎士比亚, 英语-莎士比亚, 英语-莎士比亚, 英语-莎士比亚, │
│ 物理-牛顿, 物理-牛顿, 化学-门捷列夫, 化学-门捷列夫, 生物-达尔文, 生物-达尔文, 历史-当年明月, 历史-当年明月, 地理-竺可桢, 地理-竺可桢, │
│ 政治-邓小平, 政治-邓小平, 信息-比尔盖茨, 体育-乔丹, 体育-乔丹, 周会                │
└────────────────────────────────────────────────────────────────────────────────────┘

``` 

### Suggestion: 

**Support for full-width characters will be nice.**

**Comment by firai** [comment] 2023-10-12 18:22
Duplicate of #49 and a number of other previously filed issues. I have previously provided an explanation of this at https://github.com/jazzband/prettytable/issues/213#issuecomment-1627747588. In short, this isn't caused by the library but rather by the font(s) that you're using, and there isn't anything that the library can do. You can try to use a monospace font that includes the Chinese character set, such as [Sarasa Gothic](https://github.com/be5invis/Sarasa-Gothic).

**Closed as not planned** 2023-10-12 22:19 UTC

**Comment by yeruizhi** [comment] 2023-10-13 03:09
I tried another testcase. 

![image](https://github.com/jazzband/prettytable/assets/4606635/50728b08-fdb3-4921-a508-1f633d8956b9)


In this case above, the row2 had not been wrapped because the code assume row2 (len=50) was shorter than max_width, while row1(len=100) should be wrapped. 

Prettytable wrap the string by character number counting, but ignore the fact that "full-width" takes two width while 'half-witdh" tasks one.

I think, it is about wrapping functionality, not about displaying.
