### ISSUE TITLE
`float_format` not working

### ISSUE THREAD

**Issue by watermelon0guy** [jazzband/prettytable#300] opened 2024-05-01 19:14 UTC
### What did you do?
Format floats in table using `float_format`
### What did you expect to happen?
Expect suppressing scientific notation
### What actually happened?
Nothing changed
### What versions are you using?

* OS: Fedora 40
* Python: 3.11
* PrettyTable: 3.10.0

Please include **code** that reproduces the issue.

```python
import prettytable as pt

arr = [1.3310884083630156e-05, 6.655442041815078e-06, 5.546201701512565e-06]

table = pt.PrettyTable()
table.float_format = "0.8"

table.add_row(arr)

print(table)

```

```
+------------------------+-----------------------+-----------------------+
|        Field 1         |        Field 2        |        Field 3        |
+------------------------+-----------------------+-----------------------+
| 1.3310884083630156e-05 | 6.655442041815078e-06 | 5.546201701512565e-06 |
+------------------------+-----------------------+-----------------------+
```

**Comment by hugovk** [comment] 2024-05-01 19:20
Thanks for the report, this looks like a duplicate of https://github.com/jazzband/prettytable/issues/243.

As a workaround, set the format after adding the rows:

```python
import prettytable as pt

arr = [1.3310884083630156e-05, 6.655442041815078e-06, 5.546201701512565e-06]

table = pt.PrettyTable()
table.add_row(arr)

table.float_format = "0.8"

print(table)
```
```
+------------+------------+------------+
|  Field 1   |  Field 2   |  Field 3   |
+------------+------------+------------+
| 0.00001331 | 0.00000666 | 0.00000555 |
+------------+------------+------------+
```

**Closed as not planned by hugovk** 2024-05-01 19:20 UTC
Labels: duplicate

**Comment by stuertz** [comment] 2024-11-24 19:42
> Thanks for the report, this looks like a duplicate of #243.
> 
While fixing #243 I took a deeper look, and it seems not to be a duplicate. The problem occurs, because `add_row()` initializes the table with columns, which has not been done before. In that moment the formatting params are fresh initialized with the defaults and the code does not recognize ' table.float_format = "0.8"' 

I tend to say this is not a bug, but a unsupported usage of the api. You have some possibilities:
* set the format after calling `add_row()`as stated above
* Initialize everything  on Table creation:
```python
table = PrettyTable(["a","b","c"], float_format="0.8")
table.add_row([1.3310884083630156e-05, 6.655442041815078e-06, 5.546201701512565e-06])
```
```python
table = PrettyTable(["a","b","c"], float_format="0.8")
table.add_row([1.3310884083630156e-05, 6.655442041815078e-06, 5.546201701512565e-06])
```
* or after merge of #343, this should also work 
```python
table = PrettyTable(float_format="0.8")
table.add_row([1.3310884083630156e-05, 6.655442041815078e-06, 5.546201701512565e-06])
```
